spring.application.name=service-forum
server.port=8084

spring.datasource.url=jdbc:h2:file:./.localdb/yomu_forum;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=